description: >
  Create .releaserc.json for usage with github, including CHANGELOG.md generation.
  This configuration is more advanced and creates a git tag, CHANGELOG.md and github release containing the release notes.
parameters:
  tag-format:
    default: ${version}
    description: Tag format (make sure to escape dollar signs)
    type: string
steps:
  - run:
      name: Create .releaserc.json if not already present
      command: <<include(scripts/create-changelog-github-releaserc.sh)>>
      environment:
        SEMANTIC_RELEASE_TAG_FORMAT: <<parameters.tag-format>>
